name = "ATAR"
uuid = "00839eba-23d4-4133-a7b0-e0dfc664097d"
authors = ["thecruncherau <thecruncherau@gmail.com>"]
version = "0.3.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DataFrames = "1.7.0"
Statistics = "1.11.1"
StatsBase = "0.34.5"
Test = "1.11.0"
